### ISSUE TITLE
Demo Inhalte Mehrsprachig

### ISSUE THREAD

**Issue by joachimdoerr** [FriendsOfREDAXO/cke5#1]
Momentan sind die Demo-Inhalte nur in deutsch vorhanden, es wäre schick diese auch noch in English bereit zu stellen.

**Comment by 191977** [comment]
Wenn hier noch Bedarf besteht könnte ich mich einbringen. Ich bräuchte nur noch etwas Einstiegshilfe was die Bearbeitung mit git angeht

**Comment by joachimdoerr** [comment]
@191977 sehr gerne. git ist ja soweit eigentlich nicht so schwierig einach mal ein repo auschecken und was rein puschen ggf. auch mal ein kurzes toturial suchen und etwas experimentieren. Sonst helfen auch programme wie sourcetree oder tower.

**Comment by 191977** [comment]
@joachimdoerr Ok, ich hab mir das repo mal geclont. Wenn ich es richtig seh geht es um die Texte in main.demo.php und in data.sql. Denke wir würden dann einfach durch die englische Version aus Wikipedia ersetzen oder? Wie ist den das von der Struktur her, wo sollten die englischen Versionen jetzt rein?

**Comment by joachimdoerr** [comment]
@191977 ja ich würde auch die englischen texte aus wikipedia nehmen. Ich persönlich fände es super wenn wir das mehrsprachig anbieten würden. Ggf. müsste man die Struktur auch nochmal etwas verbessern, ich glaube ich hatte Überschriften auch selbst gewählt, da wäre es gut, wenn man sich im Ganzen an die Wikipedia vorläge halten würde.

**Comment by joachimdoerr** [comment]
Seit 2019 kein Change ich denke wir können hier schließen ich werd die Mehrsprachigkeit nicht umsetzen.
