### ISSUE TITLE
Custom Schriftarten

### ISSUE THREAD

**Issue by joachimdoerr** [FriendsOfREDAXO/cke5#10]
Man kann ja bereits Standard-Schriften wählen, es wäre durchaus sinnvoll ginge dies auch mit diversen Webfonts. Diese müssten dann ins Backend eingeladen werden.

**Comment by skerbis** [comment]
Vielleicht per API aus: https://github.com/majodev/google-webfonts-helper/

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/cke5/issues/84
