### ISSUE TITLE
UI Anzeigefehler im Backend

### ISSUE THREAD

**Issue by crydotsnake** [FriendsOfREDAXO/cke5#101]
Hallo, ich nutze die aktuellste Version vom CKE5 und die aktuellste REDAXO Version. Irgendwie sieht die Frontseite vom Addon ein bisschen buggy aus.. Wollte zur Sicherheit mal eine Issue erstellen! :blush: 
![CKE5](https://user-images.githubusercontent.com/39345336/75111072-1b08b680-5636-11ea-9591-c00121a0bc70.gif)

**Comment by crydotsnake** [comment]
Nebenbei schmeißt mir die Chrome Konsole auch ein paar Fehler.. Das es an meinem file system liegt glaub ich nicht, da ich das Addon ganz normal über den Installer geladen habe.

![Bildschirmfoto vom 2020-02-23 12-20-05](https://user-images.githubusercontent.com/39345336/75111161-e5b09880-5636-11ea-869c-eb828c3ee718.png)

**Comment by skerbis** [comment]
Ich kann diesen Fehler nicht reproduzieren. Ist es eine lokale Installation?

**Comment by skerbis** [comment]
<img width="1217" alt="Bildschirmfoto 2020-03-03 um 15 31 48" src="https://user-images.githubusercontent.com/791247/75785521-278ebc80-5d64-11ea-99e0-cf03de101c1a.png">

**Comment by crydotsnake** [comment]
Ja

**Comment by MargadantLuca** [comment]
Kann ich soweit ebenfalls bestätigen. Auf lokalen Installationen ist es Fehlerhaft, auf Live-Instanzen jedoch einwandfrei.

**Comment by skerbis** [comment]
aber nur in der demo oder?

**Comment by MargadantLuca** [comment]
Richtig. Man kann dann jedoch nicht auf die Profile wechseln, da .cke5-header die Toolbar überdeckt.

Da ich bloss eine Basis-Instanz für Redaxo einrichtete, war das kein Problem für mein Vorhaben, da mein Setup danach auf Live-Servern läuft. Ich habe per Inspector eifach den Header ausgeblendet und konnte somit zu den Profilen wechseln.

Ich bin aus Neugier aber dennoch auf den Issue gestossen, und dachte mir ich teile es euch doch mal mit.

Herzlichen Dank an dieser Stelle aber auch für eure tolle Arbeit die ihr für die Community leistet!

**Comment by crydotsnake** [comment]
Vielen dank, für deine Meldung! :). 

Mich verwundert nur, wieso es produktiv (was ich nicht testen kann) funktioniert, aber lokal nicht...

**Comment by skerbis** [comment]
Es liegt an localhost vs. externe Inhalte

**Comment by skerbis** [comment]
Wer traut sich? Auf localhost prüfen und eine andere Demo oder keine Demo dann auszuliefern?

**Comment by joachimdoerr** [comment]
Gibt es jemand der hier zuliefern will?

**Comment by crydotsnake** [comment]
Ich habe mich eben nochmal mit der Thematik befasst, und habe mir das AddOn über das zip_install Addon installiert. Und diesesmal sind die Anzeigefehler von wie oben beschrieben nicht vorhanden.

Hier ist mein Systembericht:



<details>
<summary>System report (REDAXO 5.11.0-dev#9d2bcd5f6, PHP 7.3.16-1+0~20200320.56+debian10~1.gbp370a75, MariaDB 10.2.30)</summary>

| REDAXO        |                      |
| ------------: | :------------------- |
|       Version | 5.11.0-dev#9d2bcd5f6 |


| PHP           |                                |
| ------------: | :----------------------------- |
|       Version | 7.3.16-1+0~20200320.56+debian10~1.gbp370a75 |
|       OPcache | yes                            |
|        Xdebug | no                             |


| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.2.30 |
| Character set | utf8mb4         |


| Server        |               |
| ------------: | :------------ |
|            OS | Linux         |
|          SAPI | fpm-fcgi      |
|     Webserver | Apache/2.4.38 |


| Request       |              |
| ------------: | :----------- |
|       Browser | Firefox/76.0 |
|      Protocol | HTTP/1.1     |
|         HTTPS | yes          |


| Packages          |            |
| ----------------: | :--------- |
|            backup | 2.6.0      |
|          be_style | 2.10.1     |
|   be_style/redaxo | 2.10.1     |
|              cke5 | 3.7.1      |
|           install | 2.8.0-dev  |
|     media_manager | 2.9.1      |
|         mediapool | 2.8.1      |
|          metainfo | 2.7.1      |
|           project | dev        |
|         structure | 2.11.0-dev |
| structure/content | 2.11.0-dev |
|             users | 2.7.0-dev  |
|       zip_install | 1.1        |

</details>

**Comment by joachimdoerr** [comment]
1fe1d49e6955b9666b34bbc22369606f746c10a3
