### ISSUE TITLE
Reinstall / REDAXO-Setup / Backup-Import setzt Profile und Cache zurück

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/cke5#102]
Mindestens das Default-Profil wird bei einem Update von R5.x wird durch den Aufruf der Installationsroutine zurückgesetzt. Dieses sollte entweder nicht bearbeitbar sein und immer default sein sozusagen, oder bei einer (Re-)Installation nicht zurückgesetzt werden.

Gleiches gilt für eigens angelegte Profile. Diese müssen neu abgespeichert werden nach einem Backup, da sonst nicht die tatäsichlichen Profil-Einstellungen nicht im Cache landen.

**Comment by alexplusde** [comment]
Das ist im Moment wirklich ein Problem.

**Comment by joachimdoerr** [comment]
reinstall: identisch mit update, nur datenbank strukur ggf ergänzeen reparieren
redaxo re setup … keine auswirkung
update - nur datenbank assets etc
profil sollte nur initial bei einer frischen Install angelegt werden
bei größeren Änderungen löschen
und neu anlegen

**Comment by joachimdoerr** [comment]
einfach beim update das .sql nicht importieren

**Comment by alexplusde** [comment]
wenn aus irgendwelchen Gründen nach dem Setup ein reinstall passiert oder ein neuer install passiert in einem vorhandenen Setup, dann einfach nicht überschreiben.

Habe dazu auch was in petto, falls gewünscht.

**Comment by joachimdoerr** [comment]
@alexplusde gerne es ist gewünscht ;)

**Comment by joachimdoerr** [comment]
@alexplusde wie ist hier der stand willst du das für den nächsten Release beisteuern?

**Comment by alexplusde** [comment]
Urspr. hieß es, der cke5 wird fallen gelassen, deshalb habe ich mich darum nicht mehr bemüht. Ich kann es wieder auf die Agenda nehmen, falls gewünscht.

**Comment by joachimdoerr** [comment]
@alexplusde  ja ich wollte das Addon eigentlich nicht selbst weiter betreuen, habe mich aber dann doch dazu entschieden es weiter zu führen, da der cke5 der einzige editor ist der wirklich performant mit mBlock funktioniert.

**Comment by joachimdoerr** [comment]
6353ac25db965eaa282053f00b508572235679b5
