### ISSUE TITLE
Wunschfeature: Text unformatiert einfügen

### ISSUE THREAD

**Issue by dpf-dd** [FriendsOfREDAXO/cke5#107]
Danke für den Hinweis im Slack-Channel :)

Ich nutze den aktuellen CKE und habe nur einen kleinen offenen Wunsch, dann ists quasi perfekt:
Es wäre toll, wenn ich dem CKE per default sagen könnte, dass er nur unformatierten Text empfangen darf.
Aktuell muss ich immer mit SHIFT+STRG+V reinkopieren, aber das begreifen viele Redakteure nicht. Die nehmen klassisch STRG+V und fragen sich dann wo der gelbe Schrifthintergrund herkommt, wenn Daten von post.de copied&pasted worden sind... :smile:

**Comment by joachimdoerr** [comment]
@dpf-dd man müsste mal checken ob der vendor sich entsprechende konfigurieren lässt, ich bin mir da jetzt nicht sicher. Wäre schön wenn Du dem nachgehen könntest.

**Comment by joachimdoerr** [comment]
019b0238d3045eaa7667f8fcd227532c9644fe99
