### ISSUE TITLE
Custom Buttons ermöglichen

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/cke5#112]
@tbaddade möchtest du dazu was schreiben? 
- Hast du spezielle Anforderungen?

**Comment by tbaddade** [comment]
> Hast du spezielle Anforderungen?

Nein. Ich kann nur schreiben wie wir es beim Redactor machen.

Wir schreiben eigene Buttons via JS, legen diese im project AddOn unter assets ab und stehen dann bei den Profilen via EP[1] zur Verfügung.

Ein eigenes build müssen wir da nicht erstellen.

[1]
```php
    $addon = rex_addon::get('project');
    rex_extension::register('REDACTOR_PLUGIN_DIR', function (rex_extension_point $ep) use ($addon) {
        $dirs = $ep->getSubject();
        $dirs[] = $addon->getAssetsPath('redactor-plugins');

        return $dirs;
    });
```

**Comment by joachimdoerr** [comment]
https://github.com/ckeditor/ckeditor5/issues/1189

**Comment by joachimdoerr** [comment]
Wer das benötigt, kann ein eigenes npm Modul dazu schreiben und dieses in einem eigenen Build bereitstellen. Ich werd das jedenfalls nicht umsetzen. Deswegen hier erstmal Close sollte sich jemand anderes finden der das bauen will dann gerne nochmal öffnen.
