### ISSUE TITLE
Image-Upload mit autom. Größenreduzierung (wie uploader) sinnvoll

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/cke5#116]
Beim wirklich tollen Drag-Drop-Upload sollte man auch eine autom. Größenreduzierung einstellen können (analog dem uploader).

**Comment by skerbis** [comment]
Gerne. Tipps und PR welcome

**Comment by joachimdoerr** [comment]
Die Idee ist gut nur ob das vis Javascript so einfach zu realisieren bleibt fraglich. Via PHP im Cke5UploadHandler ist das jedoch definitiv machbar benötigt dann entsprechende Ressourcen und Setup-Optionen.

**Comment by joachimdoerr** [comment]
Keine Vorschlage. Close.
