### ISSUE TITLE
Minimal-Höhe des Editors wird ignoriert

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/cke5#117]
Wenn ich dem Editorfenster eine Min/Max-Höhe gebe, dann wird die Höhe ignoriert, sobald ich in das Fenster klicke.

**Comment by skerbis** [comment]
@joachimdoerr die Höhe wird zwar initialisiert. Bei Click wird automatisch wieder verkleinert und Autohöhe aktiviert.

**Comment by joachimdoerr** [comment]
Offensichtlich überschreib die neue version des Editors das von außen erzwungene min und max height setup. Die frage ist ob sich das künftig weiter anbieten lässt in der Form.

**Comment by skerbis** [comment]
Könnte man das nicht per attribute am Feld selbst steuern und aus dem Setup rauslassen?

**Comment by joachimdoerr** [comment]
wir schreiben via JS in das CKE5 DOM element ".ck-content" ein style attribute und dieses wird on focus von vendor removed. also müssen wir das anders handhaben. ich bin mir nur noch nicht so eins mit mir selbst wie genau.

**Comment by joachimdoerr** [comment]
1588f9dfe428bef26b48b20f308142cdf88c079f
