### ISSUE TITLE
Styles-Feld kann nicht in Toolbar hinzugefügt werden

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/cke5#118]
Das bekannte (und beliebte) Styles-Auswahlfeld kann nicht definiert werden, so dass es in der Toolbar erscheint.
Wäre toll, wenn es das wieder geben würde.

**Comment by skerbis** [comment]
Was für Styles?

**Comment by skerbis** [comment]
Solltest du ein solches PlugIn finden @iceman-fx gerne den Link hier hinterlegen.

**Comment by skerbis** [comment]
Wenn es so ein PlugIn für CKE5 gibt ... gerne wieder aufmachen
