### ISSUE TITLE
Toolbar über mehrere Zeilen einstellbar?

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/cke5#119]
Falls möglich, wäre das Hinzufügen von Toolbarumbrüchen (Definition von mehreren Zeilen) toll.
Dann würde man die Icons noch etwas besser sortieren lassen.

**Comment by skerbis** [comment]
Toolbar Group auf off stellen. Dann sollte die Toolbar automatisch umbrechen

**Comment by joachimdoerr** [comment]
<img width="1065" alt="Bildschirmfoto 2020-07-20 um 09 03 57" src="https://user-images.githubusercontent.com/1191549/87909162-fe976b80-ca67-11ea-9e9b-fe00583c0bfc.png">
