### ISSUE TITLE
Custom Link-Decorators nach erneutem editieren deaktiviert

### ISSUE THREAD

**Issue by 191977** [FriendsOfREDAXO/cke5#125]
Hi,

ich teste gerade das sehr coole feature mit den Custom Link-Decorators und habe einen wie folgt angelegt:

`{"buttonlink": {
                    "mode": "manual",
                    "label": "Als Button darstellen",
                    "attributes": {
                        "class": "btn btn-primary"
                    }
                }
}`

Mit Speichern des Moduls passt die Ausgabe im Frontend jedoch ist der Dekorator beim erneuten Editieren des Moduls auf inaktiv gesetzt und nach erneutem Speichern ist dann auch die Ausgabe zurückgesetzt. Lässt sich auch schon im BE bei klick auf "übernehmen" nachvollziehen.

**Comment by joachimdoerr** [comment]
Hello @191977, kannst Du mir bitte zum Testen ein fertigen Modul-Input liefern. Danke!

**Comment by 191977** [comment]
Klar. 
Also cke-Profil "test_linkdecorator" mit Link-Decorator

```
{"buttonlink": { "mode": "manual", "label": "Als Button darstellen", "attributes": { "class": "btn btn-primary" } } }
```

Input:
```
<textarea class="form-control cke5-editor" data-profile="test_linkdecorator" data-lang="<?php echo \Cke5\Utils\Cke5Lang::getUserLang(); ?>" data-content-lang="<?php echo \Cke5\Utils\Cke5Lang::getOutputLang(); ?>" name="REX_INPUT_VALUE[1]">REX_VALUE[1]</textarea>
<?php
$mform = new MForm();
$mform->addTextAreaField('2', ['class' => 'cke5-editor', 'data-lang' => \Cke5\Utils\Cke5Lang::getUserLang(), 'data-content-lang' => \Cke5\Utils\Cke5Lang::getOutputLang(), 'data-profile' => 'test_linkdecorator']);

echo $mform->show();

```

**Comment by joachimdoerr** [comment]
Dank @191977  das Problem liegt im Vendor: https://github.com/ckeditor/ckeditor5/issues/6571

am besten mit `data-class` arbeiten und via str_replace im Modul `output` dann zu class ersetzen lassen.

```
{"buttonlink": { "mode": "manual", "label": "Als Button darstellen", "attributes": { "data-replace-class": "btn btn-primary" } } }
```

```
<?php echo str_replace('data-replace-class','class',$output); ?> 
```

**Comment by joachimdoerr** [comment]
Ich schließe hier da es sich um ein Vendor issue handelt und wir da wenig/nichts machen können.

**Comment by 191977** [comment]
Hallo @joachimdoerr , danke dir! Vor allem auch für den workaround!

**Comment by 191977** [comment]
Hi nochmals @joachimdoerr 
es scheint leider doch nicht an den Klassen zu liegen. Wie ich eben bemerkt habe wird der Decorator auch für das Beispiel aus der Doku nicht gespeichert. 
```
{"openInNewTab": {
                    "mode": "manual",
                    "label": "Open in a new tab",
                    "attributes": {
                        "target": "_blank",
                        "rel": "noopener noreferrer"
                    }
                }
}
```
Hätte ich gleich checken sollen.
Auch ein vendor-Thema? Dann sollte das feature derzeit vielleicht eher wieder raus aus dem addon oder?
