### ISSUE TITLE
MBlock is available check in Demo

### ISSUE THREAD

**Issue by joachimdoerr** [FriendsOfREDAXO/cke5#126]
Die Demo soll nur dann ausgegeben werden sofern MBlock vorhanden ist.

**Comment by joachimdoerr** [comment]
Requires in der package.yml lässt den Navigation Punkt nicht ausblenden.

**Comment by skerbis** [comment]
Ne die Seite muss per php eingebunden oder ausgeblendet werden

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/cke5/pulls
