### ISSUE TITLE
CKE5 Tabellen Plugin integrieren 

### ISSUE THREAD

**Issue by joachimdoerr** [FriendsOfREDAXO/cke5#13]
Es wäre gut wenn das Tabellen Plugin integriert würde, das ist momentan leider noch nicht freit entwickelt. Aber sobald eine Beta raus ist könnte man mal schauen ob es eingebaut werden kann.

**Comment by mhut47** [comment]
ja bitte. Danke für das tolle Addon

**Comment by joachimdoerr** [comment]
https://github.com/ckeditor/ckeditor5-table/releases

**Comment by joachimdoerr** [comment]
85515f9e147826c16c25480b3e62b9354578ab7e
80105da50a4bab1f577c1c6fcb785216c37d265e
18bfe5f420d68d31dcbbe9ce87daa709522c6ee7
1150cd558529d4a5f13532fb253ae82b46e58c38
4e431171bf863bcaff43d0f3ef18aa91bd013cfe
199f3d24a1f184793959f1fdb31c7eb46449dd2e
