### ISSUE TITLE
CSS-Fehler im Editor

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/cke5#131]
![image](https://user-images.githubusercontent.com/3855487/107148995-81c1d580-6956-11eb-9cfe-b0ad3eea6a50.png)

Habe das nur ich? Kleben nachfolgende Absätze und Überschriften an vorangegangenen Listen?

**Comment by skerbis** [comment]
Ja, das scheinst nur du zu haben. 
<img width="1127" alt="Bildschirmfoto 2021-02-19 um 17 24 09" src="https://user-images.githubusercontent.com/791247/108531709-4a004980-72d7-11eb-87b1-35b151c937c9.png">
