### ISSUE TITLE
Link Decorators

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/cke5#132]
Moin, keine Ahnung ob das am CKE oder am AddOn liegt,
Wenn ich defaultValue: true setze ist der Decorator wie gewünscht vorausgewählt.
Beim nächsten bearbeiten des Links ist er jedoch wieder deaktiviert und man muss ihn manuell setzen.

**Comment by skerbis** [comment]
Die Keys müssen in Kleinschrift sein.
