### ISSUE TITLE
Nach Update müssen Profile neu gespeichert werden

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/cke5#135]
Ich hab das bei allen Installatione und schon seit langem. Nach jedem Update muss ich die Profile neu speichern. Vergesse ich das Mal, hat der Kunde ALLE Optionen zur Verfügung und versaut mir den Kontent.

**Comment by joachimdoerr** [comment]
381274e9e75d87923e3cd012f7c6bd12339a9615

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/cke5/pull/137
