### ISSUE TITLE
Variablen aus Sprog vorschlagen lassen

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/cke5#138]
Ich nutze Moco als Agentursoftware und hier gibt es ein neues Feature. Tippt man { bekommt man alle zugeordneten Variablen als Liste vorgeschlagen: https://www.mocoapp.com/blog/704-wysiwyg-variablen-deluxe
Ich lasse meine Redakteure Sprog variablen nutzen. Es wäre ziemlich cool, wenn man das integrieren könnte.
Moco nutzt hierzu: https://zurb.github.io/tribute/example/
Man könnte z.B. alle Variablen mit {{cke.*}} listen lassen.

**Comment by skerbis** [comment]
Ich schätze dass dies eher eine "Baustelle" für Sprog allgemein ist. Meinst du nicht auch? Denn die gesamte Logik dahinter wäre doch für alle Editoren interessant.

**Comment by skerbis** [comment]
denke das wird erstmal nichts

**Comment by joachimdoerr** [comment]
Hier wäre eher ein eigenes Plugin angebracht, ich finde das generell interessant und würde das auch weiter verfolgen wollen: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html

**Comment by marcohanke** [comment]
Cool, ich fürchte ich kann dich nicht viel unterstützen dabei. Falls doch gib mir bescheid.

**Comment by marcohanke** [comment]
Wobei vermutlich auch in Sprog Hand angelegt werden müsste. Man will ja nicht automatisch alle Variablen zur Verfügung stellen, also bräuchte es eine Checkbox zur Freigabe bestimmter Variablen. Außerdem müsste man irgendwie die Sprachen handeln. Nur die Variablen der aktuellen Sprache anzeigen? Oder alle Sprachen mit lang-tag dahinter ?

**Comment by joachimdoerr** [comment]
Aus heutiger Sicht ist das eher unrealistisch sowas zu bauen, ich müsste dafür das CKE5 Plugin bauen und für die Abhängigkeiten zu Sprog in Sprog selbst auch noch einiges erweitern, dazu fehlt mir persönlich leider die Zeit. Deswegen an der stelle close.
