### ISSUE TITLE
Image-Resize-Buttons Option ist ohne Funktion

### ISSUE THREAD

**Issue by AndiLeni** [FriendsOfREDAXO/cke5#141]
Das Aktivieren und Deaktivieren der Option `Image Resize Buttons` bleibt erfolglos.

Wenn in den `Image Resize Options` kein Eintrag vorhanden ist, schlägt das Initialisieren des Editors fehl.

Auszug aus dem JS Log:
````js
CKEditorError: imageresizebuttons-missing-icon {"name":"imageResize:","value":"","icon":""}
Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/…pport/error-codes.html#error-imageresizebuttons-missing-icon
    o ckeditorerror.js:64
    _registerImageResizeButton imageresizebuttons.js:116
    create componentfactory.js:110
    fillFromConfig toolbarview.js:281
    fillFromConfig toolbarview.js:277
    register widgettoolbarrepository.js:156
    afterInit imagetoolbar.js:48
````

**Comment by skerbis** [comment]
@joachimdoerr 

- Wenn Image Resize Buttons deaktiviert werden, wenn zuvor welche definiert wurden, werden diese weiterhin ausgespielt. Es fehlt anscheinend eine Prüfung ob deaktiviert wurde. 
- Wenn aktiviert / deaktiviert aber keine angelegt erscheint der Fehler oben von @AndiLeni

**Comment by lkohlfuerst** [comment]
Ich habe als Workaround die Fehlermeldung weg gebracht, indem ich in der Datenbank Tabelle die Felder `image_resize_unit`, `image_resize_options` und `image_resize_options_definitions` auf NULL gesetzt habe und dann die Option "Image-Drag&Drop-Upload" deaktiviert habe

**Comment by joachimdoerr** [comment]
Im nächsten Release wird das Problem behoben sein. Der Commit dafür ist bereits fertig und muss noch gepusht werden.
