### ISSUE TITLE
Sprache fehlt

### ISSUE THREAD

**Issue by AndiLeni** [FriendsOfREDAXO/cke5#142]
Das öffnen des Dropdown menüs im Link Menü löst folgenden Fehler aus:
![grafik](https://user-images.githubusercontent.com/13385771/133936221-d6d8c466-e220-4e3d-8238-f04c79b2cfb9.png)

`Uncaught CKEditorError: this.locale is undefined`

Danach werden Änderungen am Content nicht mehr angezeigt, aber dennoch gespeichert.
Speichern und erneutes öffnen lässt den Editor wieder funktionieren (bis das dropdown menü erneut geöffnet wird).

**Comment by joachimdoerr** [comment]
Das Problem liegt am npm Modul und daran das wie im npm Modul globale Variablen zwischen den einzelnen Methoden propagiert werden oder auch nicht. Das ganze sollte mit dem Vendor update und den nötigen Breaking-Change Anpassungen des RexLink npm Modules korrigiert sein.
