### ISSUE TITLE
Profilnamen ohne Bindestrich/Minuszeichen

### ISSUE THREAD

**Issue by danspringer** [FriendsOfREDAXO/cke5#143]
Wenn man ein Profil anlegt und diesem einen Namen wie z.B. **text-area** [Text MINUS Area] anstatt "textarea" oder "text_area" gibt, wird der Editor / das Editorprofil nicht richtig geladen und man rauft sich die Haare, woran das nun liegen könnte :-)

Entweder sollte man die Eingabe dieses Zeichens verbieten oder das evtl. in der Doku vermerken.

**Comment by joachimdoerr** [comment]
3748fd12c79824a90ff62c32ec407132e0c07ba9
