### ISSUE TITLE
Warning: Field "theme" does not exist in result! in redaxo/src/core/lib/sql/sql.php on line 794

### ISSUE THREAD

**Issue by greatif** [FriendsOfREDAXO/cke5#146]
Nach einem Update auf Version 4.3.0-beta2 läuft das Backend mit Warnings voll:

Warning: Field "theme" does not exist in result! in redaxo/src/core/lib/sql/sql.php on line 794

Re-Install ändert nichts.
Deaktiviere ich cke5 verschwindet die Warnung.

![scr01](https://user-images.githubusercontent.com/8527203/140164206-b32d7603-c5db-41d2-9523-a95801c025e2.jpg)

Woran könnte das liegen?

**Comment by skerbis** [comment]
- Bitte wechsele zur vorherigen CKE5 final Version. Theme wird es erst ab REDAXO 5.13 geben.

**Comment by greatif** [comment]
> 
> 
>     * Bitte wechsele zur vorherigen CKE5 final Version. Theme wird es erst ab REDAXO 5.13 geben.

Ahhh stimmt, "dunkle Aussichten" werfen ihre Schatten voraus... :-)

Bin wieder zurück gewechselt, Problem behoben.
