### ISSUE TITLE
rexImage-Einbindung mit default-Werten führt zu "broken image"

### ISSUE THREAD

**Issue by dpf-dd** [FriendsOfREDAXO/cke5#147]
Aus dem Slack-Channel...
Ich habe jetzt zum ersten Mal das rexImage-Feature genutzt um ein Bild direkt in den Editor zu holen. In den Settings des Profils ist kein eigener Medien-Pfad und auch kein Medientyp angegeben, sodass die Ausgabe im Editor mit dem Default-img-src-Pfad /media/ erfolgen müsste. Tut es aber nicht. Ich bekomme ein "Broken Image" Icon und beim Inspizieren des Quelltexts sehe ich auch schon den Fehler... Im img-Tag ist als src // angegeben.
Wenn ich jetzt einen Medientype original (und OHNE irgendwelche Effekte) erstelle und diesen im Profil des Editors hinterlege, dann ZACK, klappt alles wie geplant und im Editor wird das Bild mit korrektem Pfad /media/original/ geladen und angezeigt.
Kann das jemand reproduzieren? (Redaxo 5.12.1) (edited)

**Comment by skerbis** [comment]
Leider können wir es aktuell nicht reproduzieren. Wenn du mehr Details hast gerne wieder öffnen.
