### ISSUE TITLE
Tabellen leere figure mit &nbsp; 

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/cke5#148]
Unterhalb von Tabellen finden sich leere

```html
<figure>
    &nbsp;
</figure>
```php

Sie sind erst nach dem Speichern des Blocks da

**Comment by joachimdoerr** [comment]
Das Problem wird sicher durch den Vendor verursacht. Ich wüsste nicht welcher Programm Part so etwas hinzufügen könnte.

**Comment by skerbis** [comment]
Sollte hiermit erledigt sein. 
https://github.com/ckeditor/ckeditor5/pull/10814

**Comment by skerbis** [comment]
@joachimdoerr scheint beim Vendor jetzt gefixt
