### ISSUE TITLE
4.3.0-beta3: Editor wird nicht initialisiert

### ISSUE THREAD

**Issue by TobiasKrais** [FriendsOfREDAXO/cke5#149]
Begründung ist in der Browserkonsole zu finden:
![Bildschirmfoto von 2021-11-25 17-50-30](https://user-images.githubusercontent.com/4131072/143478976-24bfdc85-de92-4303-bd74-cf09b951b945.png)

**Comment by skerbis** [comment]
bitte mal die aktuelle 5-dev testen

**Comment by TobiasKrais** [comment]
Leider immernoch der gleiche Fehler.

**Comment by skerbis** [comment]
Hast du die Profile mal neu gespeichert? Ich kann es nicht reproduzieren

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/cke5/issues/150

**Comment by TobiasKrais** [comment]
Ja, das war es. Profile gespeichert und alles läuft. Danke!

**Comment by TobiasKrais** [comment]
Beim Upgrade auf die aktuelle Version müssen die Profile in jeder Installation neu gespeichert werden. Lässt sich das automatisieren?

**Comment by skerbis** [comment]
Wir haben das beim cke5 gelöst. Man könnte es sich dort abschaben

**Comment by TobiasKrais** [comment]
Oh, stimmt den CKEditor ist ja ein anderes Addon. Sorry...
