### ISSUE TITLE
Muss man windows.matchMedia auf Existenz prüfen?

### ISSUE THREAD

**Issue by christophboecker** [FriendsOfREDAXO/cke5#155]
Ist da so funktionabel?
https://github.com/FriendsOfREDAXO/cke5/blob/c7d0b0c90edae7857786c47537c16870d8afa294/assets/cke5.js#L19-L34
In Zeile 20 wird sicherheitshalber überprüft, ob `windows.matchMedia` überhaupt existiert, aber in 23 wird es als selbstverständlich angenommen.

**Comment by skerbis** [comment]
Danke
