### ISSUE TITLE
Fettschrift wird nicht entfernt

### ISSUE THREAD

**Issue by TobiasKrais** [FriendsOfREDAXO/cke5#157]
https://user-images.githubusercontent.com/4131072/150678259-020a8480-8741-47e4-98c6-bd51bf744455.mp4

Ein Text - hier Überschrift 1 - ist Fett geschrieben. Die Fettschrift wird entfernt und ist nach dem Speichern des Blocks wieder da.

**Comment by skerbis** [comment]
@TobiasKrais ...  deaktiviere das Source-Code Editing. Das ist buggy im aktuell mitgelieferten Vendor.

**Comment by TobiasKrais** [comment]
SourceEditing deaktiviert und es funktioniert.

**Comment by joachimdoerr** [comment]
Sollte via Vendorupdate gefixt sein das Problem.
