### ISSUE TITLE
custom css werden nicht mehr geladen

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/cke5#159]

**Comment by joachimdoerr** [comment]
@skerbis kannst du das bitte nochmal ausführen mir ist nicht klar welches CSS gemeint ist in welchem Kontext.

**Comment by skerbis** [comment]
Die https://github.com/FriendsOfREDAXO/cke5/tree/master/custom_data werden nicht geladen. 
Hier sollte die eigene Darstellung in den Editor eingeschleust werden.

**Comment by joachimdoerr** [comment]
Ich wüsste nicht warum es nicht funktionieren sollte: https://github.com/FriendsOfREDAXO/cke5/blob/master/lib/Cke5/Provider/Cke5AssetsProvider.php#L28-L37
ggf. war das file in Deiner Installation nicht vorhanden?
die Provider Methode wird in der boot.php aufgerufen: https://github.com/FriendsOfREDAXO/cke5/blob/master/boot.php#L17
Vielleicht hat der user auch nicht dir korrekte Berechtigung?
Check mal bitte, ich hier aber vorerst zu.
