### ISSUE TITLE
CSS: Absatz nicht wie Zeilenumbruch layouten

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/cke5#163]
![image](https://user-images.githubusercontent.com/3855487/156130957-fa36c844-5df3-4a2e-a42e-56adbd17e15c.png)

Hier ist ein Absatz versteckt, die Zeile liegt aber so nah an einer anderen, dass man das nicht erkennt. Standardmäßig sollten hier ein paar Pixel mehr Abstand sein als in einem regulären Zeilenumbruch.

**Comment by skerbis** [comment]
Da funkt dein eigenes CSS dazwischen würde ich sagen .
<img width="560" alt="Bildschirmfoto 2022-03-01 um 11 41 03" src="https://user-images.githubusercontent.com/791247/156154412-e9609236-3eae-4e71-ae82-3bd49565481f.png">

**Comment by alxndr-w** [comment]
Dann prüfe ich das. Danke!

**Comment by alxndr-w** [comment]
Tatsächlich kommt bei mir da auch im Frontend ungültiges HTML raus:

![image](https://user-images.githubusercontent.com/3855487/156184872-bdbef060-fdfa-49a8-b39c-cc58ef0d78a4.png)

**Comment by alxndr-w** [comment]
Ich habe das Problem nun erneut wieder - es scheint vom be_styles-Addon verursacht.

![image](https://user-images.githubusercontent.com/3855487/203085747-5265940e-a968-4664-ac95-ddd74e00c521.png)


Meine Frage für mich wäre daher: Warum sieht's bei dir richtig aus?

**Comment by joachimdoerr** [comment]
@skerbis @alxndr-w, was können wir tun um das zu fixen?

**Comment by alxndr-w** [comment]
Ich denke schon, indem man wieder margin-bottom hinzufügt. Wenn ui-kit nicht bei euch drin ist, müsste es ja dasselbe Verhalten erzeugen.

**Comment by skerbis** [comment]
Tritt das nur beim CKE5 auf?

**Comment by joachimdoerr** [comment]
also ich kann das nicht nachstellen, ohne ui-kit sind die Abstände wie sie sein sollten.
