### ISSUE TITLE
Drag & drop Mediaupload REDAXO 5.13.1

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/cke5#164]
Funktioniert nicht mehr

Im Log erhalte ich

Warning | rename(/httpdocs/media/logo_mytrainer.png,/httpdocs/media/logo_mytrainer.png): No such file or directory | redaxo/src/core/lib/util/file.php | 179
-- | -- | -- | --

Ein Upload findet nicht statt. Es scheint jedoch so, aber im Medienpool kommt nichts an. 
*pfade sind gekürzt*

**Comment by skerbis** [comment]
@gharlan kann das mit den Änderungen in REDAXO 5.13.x zusammenhängen (Mediensyncmethoden?) 
Leider erhalte ich außer der Warnung keine weiteren konkreten Meldungen im Log. 
Die betreffende Class findet sich hier: https://github.com/FriendsOfREDAXO/cke5/blob/master/lib/Cke5/Handler/Cke5UploadHandler.php

**Comment by gharlan** [comment]
> pfade sind gekürzt

Es ist aber also wirklich so, dass da eine "Umbenennung" ohne sichtbare Änderung im Dateinamen versucht wird?

**Comment by gharlan** [comment]
Ich habe gerade grob geschaut. Es könnte tatsächlich ein weiterer Bug im Mediapool sein. Mach am besten mal ein Ticket im Core auf, damit ich es nicht vergesse.

**Comment by skerbis** [comment]
Vielleicht macht es Sinn die neuen Methoden zu verwenden. Kannst du nen Hint geben wo ich da schauen muss. Ich blicke da noch nicht durch. Issue werde ich erstellen

**Comment by skerbis** [comment]
in aktuellem Core gefixt.
