### ISSUE TITLE
YForm + CKE5: Inhalt wird nicht übernommen

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/cke5#165]
Szenario: Ich öffne einen YForm-Datensatz, der eine cke5-Editor-Textarea enthält. Ich gehe in den Editor, markiere den gesamten Text und drücke Strg+V zum Einfügen (und damit überschreiben). Anschließend auf Speichern.

Der Datensatz wird gespeichert, jedoch blieb der alte Text erhalten. Es wirkt, als ob das Einfügen allein nicht triggert, dass die dargestellten Inhalte auch in die Textarea geschrieben werden.

**Comment by skerbis** [comment]
Welche yform version 
Welche cke5 Version ?

**Comment by alxndr-w** [comment]
<details>
<summary>System report (REDAXO 5.13.2, PHP 7.4.28, MySQL 5.7.37)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.13.2     |


| PHP           |            |
| ------------: | :--------- |
|       Version | 7.4.28     |
|       OPcache | no         |
|        Xdebug | no         |


| Database      |              |
| ------------: | :----------- |
|       Version | MySQL 5.7.37 |
| Character set | utf8mb4      |


| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | cgi-fcgi   |
|     Webserver | Apache     |


| Request       |                      |
| ------------: | :------------------- |
|       Browser | Chrome/100.0.4896.75 |
|      Protocol | HTTP/2.0             |
|         HTTPS | yes                  |


| Packages                          |              |
| --------------------------------: | :----------- |
|                      accessdenied | 1.0.6        |
|                            across | 4.0.0-dev1   |
|                           adminer | 1.9.2        |
|                            backup | 2.8.0        |
|                       be_password | 2.0.0        |
|                          be_style | 3.0.1        |
|               be_style/customizer | 3.0.1        |
|                   be_style/redaxo | 3.0.1        |
|                   be_style_fluent | 3.1.1        |
|                          be_tools | 1.7.3        |
|                           bloecks | 3.1.1        |
|                  bloecks/cutncopy | 3.1.1        |
|                      cache_warmup | 3.7.0        |
|                              cke5 | 5.0.5        |
|                   consent_manager | 3.0.4        |
|                           cronjob | 2.8.2        |
|                           cropper | 1.3.0        |
|                         developer | 3.9.0        |
|                   email_templates | 1.0.0-beta-1 |
|                             feeds | 3.1          |
|                        focuspoint | 4.0.0        |
|                   global_settings | 2.8.1        |
|                          icecoder | 3.0.0        |
|                           install | 2.9.3        |
|                       maintenance | 2.7.3        |
|                          markitup | 3.7.1        |
|            markitup/documentation | 1.1.0        |
|                            mblock | 3.4.4        |
|                     media_manager | 2.12.1       |
|                         mediapool | 2.11.2       |
|                          metainfo | 2.8.4        |
|                             mform | 6.1.2        |
|                        mform/docs | 1.1          |
|                            minify | 2.2          |
|                         phpmailer | 2.11.1       |
|                           project | dev          |
|                   project_manager | 1.3.7        |
|            project_manager/client | 1.1.0        |
|                             qanda | 2.0.9        |
|                  quick_navigation | 5.2.1        |
|                         redactor2 | 4.2.1        |
|                         search_it | 6.9.0        |
|           search_it/documentation | 6.9.0        |
|                          speed_up | 1.0.5        |
|                             sprog | 1.3.0        |
|                         structure | 2.13.2       |
|                 structure/content | 2.13.2       |
|                 structure/history | 2.13.0       |
|                  structure_tweaks | 1.4.0        |
|                             theme | 1.3.3        |
|                          ui_tools | 1.2.1        |
| ui_tools/bootstrap-datetimepicker | 4.17.47      |
|        ui_tools/jquery-minicolors | 2.4.0        |
|                ui_tools/selectize | 0.2.0        |
|                          uploader | 2.3.0        |
|                               url | 2.0.1        |
|                       usage_check | 2.3          |
|                             users | 2.8.2        |
|                            watson | 2.2.0        |
|                     xoutputfilter | 3.0.0-beta1  |
|              xoutputfilter/abbrev | 3.0.0        |
|             xoutputfilter/backend | 3.0.0        |
|       xoutputfilter/documentation | 1.0.0        |
|            xoutputfilter/frontend | 3.0.0        |
|       xoutputfilter/import_export | 3.0.0        |
|                              ycom | 4.0.6        |
|                         ycom/auth | 4.0.6        |
|                        ycom/group | 4.0.6        |
|                             yform | 4.0.2        |
|                       yform/email | 4.0.2        |
|                     yform/manager | 4.0.2        |
|                       yform/tools | 4.0.2        |
|             yform_spam_protection | 1.2.1        |
|                   yform_usability | 2.0.3        |
|                          yrewrite | 2.8.3        |
|                       zip_install | 1.1          |

</details>

**Comment by skerbis** [comment]
Exakt so getestet wie von Dir beschrieben. Der Fehler tritt bei mir nicht auf. 
100.0.4896.75 (Offizieller Build) (x86_64)
Konnte es aber nicht unter Windows testen. 
Vielleicht grätscht da was anderes rein? redactor2 vielleicht? 
(CKE5 in Kombi mit redactor (nicht2) funzt bei mir)

**Comment by alxndr-w** [comment]
Ich mach dir bei Zeiten mal einen Screencast und dann schau ich auch mal, ob das deaktivieren von redactor etwas bewirkt. Leider komme ich heute nicht mehr dazu.
