### ISSUE TITLE
Profile-Name lässt nicht mehr als 18 Zeichen zu

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/cke5#166]
**Description / Beschreibung**
Profile-Name lässt nicht mehr als 18 Zeichen zu. Ich benötige aber mehr Zeichen :)

**Affected versions / Verwendete Versionen**

REDAXO: 
PHP:
Database:
Browser: 
AddOns:

**Did it whoops? / Whoops erhalten?**

**Comment by joachimdoerr** [comment]
Das Problem wird im nächsten Release behoben sein, der entsprechende Commit muss noch von mir gepusht werden.
