### ISSUE TITLE
List Style - OFF - funktioniert nicht

### ISSUE THREAD

**Issue by steri-rex** [FriendsOfREDAXO/cke5#168]
Ich hätte gerne das man bei der Aufzählungsliste und bei der nummerierten Liste KEIN Drop Down hat wo man die List Styles auswählen.
Also habe ich "Schafft die Option List-Styles wählen zu können" im Profil auf OFF gestellt (war vorher auf ON). 
Auch nach einem hard refresh im Browser ist immer noch das Drop Down bei den Listen zu sehen und man kann andere List Styles wählen.
Im "Light" Profil wo ich nichts verändert habe und dies auch auf "Off" gestellt ist, ist trotzdem auch das Drop Down.

**Comment by joachimdoerr** [comment]
@steri-rex wenn du die cke5profiles.js dafür mal bereitstellen könntest. es wäre auch wichtig zu wissen ob diese neu generiert wurde.

**Comment by steri-rex** [comment]
[cke5profiles.js.zip](https://github.com/FriendsOfREDAXO/cke5/files/11849540/cke5profiles.js.zip)
Hier die cke5profiles.js
