### ISSUE TITLE
z-index Problem mit Linkbox bzw. rex-nav-main

### ISSUE THREAD

**Issue by fietstouring** [FriendsOfREDAXO/cke5#171]
**Description / Beschreibung**
cke5 Linkbox verschwindet unter rex-nav-main wegen dessen z-index.

**Affected versions / Verwendete Versionen**
Redaxo 5.14.3.

![Bildschirmfoto 2023-03-10 um 11 07 14](https://user-images.githubusercontent.com/1846849/224288317-678dc6d9-6f27-423e-b529-27337703b323.png)

**Comment by skerbis** [comment]
Welcher Browser? 
Welche Fensterbreite?

Ich kann es in meinen Tests nicht reproduzieren aktuell.

**Comment by joachimdoerr** [comment]
Kann ich auch nicht nachstellen. Deswegen vorerst mal close.
