### ISSUE TITLE
style feature

### ISSUE THREAD

**Issue by steri-rex** [FriendsOfREDAXO/cke5#172]
ich möchte gerne in einem Absatz eine Wortgruppe markieren können und auszeichnen können - z.b.
`<p>Im Absatz <span class="myclass">die Wortgruppe auszeichnen<span> wäre toll!</p>`
Geht das nur mit dem style Feature?
https://ckeditor.com/docs/ckeditor5/latest/features/style.html
Wenn ja wäre es super das einzubinden.

**Comment by steri-rex** [comment]
danke für die Info - aber wie bekomme ich das Plugin im die Toolbar? Bei den Toolbar Elementen in der List ist "style" nicht dabei - wenn ich es selber dazu schreibe geht der ganze Editor nicht mehr.
Wenn ich es unter den Optionen so wie folgt zu ergänzen versuche - klappt es auch nicht
`{
        plugins: [ Style ],
        toolbar: {
            items: [
                'style',
                // More toolbar items.
                // ...
            ],
        },
        style: {
            definitions: [
                {
                    name: 'Article category',
                    element: 'h3',
                    classes: [ 'category' ]
                },
                {
                    name: 'Info box',
                    element: 'p',
                    classes: [ 'info-box' ]
                },
            ]
        }
    }`

**Comment by skerbis** [comment]
Schau mal in die Readme https://github.com/FriendsOfREDAXO/cke5#example-extra-options

**Comment by joachimdoerr** [comment]
Es wird eine integration im nächsten Release geben siehe: https://github.com/FriendsOfREDAXO/cke5/issues/152
