### ISSUE TITLE
Ersatz für pasteplaintext

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/cke5#174]
Da das Plugin nicht mehr kompatibel ist und somit nicht mehr im AddOn zur Verfügung steht wird der Content nicht mehr sauber eingefügt. Leider funktioniert auch https://ckeditor.com/docs/ckeditor5/latest/features/pasting/paste-plain-text.html  nicht wirklich zumindest bei Verwendung des Safari Browsers. 

Es besteht die Gefahr das vor allem Bilder mit fremder Quelle im Text eingefügt wird.

**Comment by joachimdoerr** [comment]
e4a813c3f7afae870b41f6ddb9ecae8c8b16b325
