### ISSUE TITLE
rexImage filtert den Medienpool nach "Image Resize Unit" und nicht nach "Erlaubte Medien-Typen"

### ISSUE THREAD

**Issue by mbodon** [FriendsOfREDAXO/cke5#175]
Beim aktuellsten CKE5 funktioniert bei mit der **rexImage** nicht, es werden im Medienpool nur Bilder mit der Endung **%** oder **px** angezeigt - je nach Einstellung im Feld **Image Resize Unit**. Das Eingabefeld “**Erlaubte Medien-Typen**” wird leider nicht berücksichtigt. Ich denke das könnte ein BUG sein …

**Comment by mbodon** [comment]
in der Datei redaxo/src/addons/cke5/lib/Cke5/Creator/Cke5ProfilesCreator.php habe ich mal die Zeilen 317-319 auskommentiert und mein Problem war weg ... aber ob ich damit eine anderen Fehler irgendwo erzeuge?

**Comment by joachimdoerr** [comment]
e4a813c3f7afae870b41f6ddb9ecae8c8b16b325
