### ISSUE TITLE
Waring in den Logs sobald ein Profil aufgerufen wird im Backend

### ISSUE THREAD

**Issue by mbodon** [FriendsOfREDAXO/cke5#176]
wenn ein Profil aufgerufen wird im Backend erschein ein Warning in den Log-Files
Undefined array key "styleEditing"
Datei: redaxo/src/addons/cke5/lib/Cke5/Creator/Cke5ProfilesCreator.php:425
URL: domain/redaxo/index.php?page=cke5/profiles/overview&func=edit&list=b27e9c07&start=0&send=1&id=2

**Comment by joachimdoerr** [comment]
e4a813c3f7afae870b41f6ddb9ecae8c8b16b325
