### ISSUE TITLE
Bei Verwendung der API Funktion -> Fehler

### ISSUE THREAD

**Issue by mbodon** [FriendsOfREDAXO/cke5#177]
cke5 ver. 6.0.0
Bei Verwendung der API-Funktion (wie in der Hilfe) erscheint leider eine Fehlermeldung:

Call to undefined method Cke5\Creator\Cke5ProfilesApi::addProfile()

**Comment by joachimdoerr** [comment]
Die Methode war auf Deprecated gesetzt https://github.com/FriendsOfREDAXO/cke5/commit/66b5f1dac3ba0fcb1cf69d09feb61efc8255f861#diff-90c4fd2d48c9aa81d6150f702aa581636c9d61e5d3a0246eede96f062bf0ea8eL40
und wurde entsprechend wie angekündigt entfernt. Wenn das noch in der Doku ist dann sollte es da auch noch rausfliegen. 
@skerbis kannst Du mal schauen

**Comment by joachimdoerr** [comment]
Ich hab die Methode nochmal hinzugefügt: c479bf39157df0e7bc03ba3d5c3bd23282262693
Sie ist durchaus sinnvoll und muss so ja nicht weiter gepflegt werden.
