### ISSUE TITLE
Redaxo-Instanz in Unterordner => Image-/Link-Ausgabe fehlerhaft

### ISSUE THREAD

**Issue by dpf-dd** [FriendsOfREDAXO/cke5#181]
Ich habe eine Redaxo-Instanz in einem Unterordner laufen (yRewrite-Domain `abc.de/xxx/yyy/`). Wenn ich jetzt im CKE ein Bild hinzufüge, dann landet für die Bildausgabe folgender Code von CKE im Quelltext: `/index.php?rex_media...` - was im Frontend zu "broken images" führt, denn die URL müsste korrekt `/xxx/yyy/index.php?rex_media...` lauten.

Ich habe für mich einen Workaround gefunden und bearbeite meinen Moduloutput entsprechend mit:
```
$editor = 'REX_VALUE[id=1 output=html]';
$editor = str_replace('/index.php?rex_media', '/xxx/yyy/index.php?rex_media', $editor);
```

EDIT:
Das gleiche Problem tritt auf, wenn ich im CKE etwas aus dem Medienpool verlinke - dann steht im Quelltext `href="/media/...` statt `href="/xxx/yyy/media"`

Die Lösung für die Probleme wäre, dass das CKE-AddOn die yRewrite-Domaineinstellung abfragt und ggf. Unterordner erkennt und entsprechend "durchschleift". Ich habe aber keine Ahnung, ob das möglich ist oder ob die Generierung der "falschen" Pfade schon im Vendor passiert... :(

REDAXO: 5.15.1 
PHP: 8.2.7
Database: MariaDB 10.11.3
AddOns: CKE 5.2.0

Hinweis: Leider kann ich in betreffendem Projekt CKE nicht auf 6.x updaten. Es müsste also evtl. geprüft werden, ob dieses Problem nur in der 5.2.0 besteht. Meine Vermutung ist, dass dieser Bug in der 6.x ebenfalls drin ist.

**Comment by skerbis** [comment]
fixed: https://github.com/FriendsOfREDAXO/cke5/releases/tag/6.0.3
