### ISSUE TITLE
Anker Links

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/cke5#184]
Ich gebe jedem Block immer die REX_SLICE_ID als ID mit und zeige diese im Backend im jeweiligen Block an.
Der Redakteur kann dann im CKE die REX_SLICE_ID als Anker hinterlegen.

Soweit so gut.
Problematisch wird es, wenn man auf einen Anker einer anderern Seite verlinken will. Dann muss das ganze Manuell eingetragen werden und nicht mehr über die Redaxo LinkMap.

Eine einfache Lösung wäre ein weiteres Input zum manuellen Eintragen des Ankers. Eleganter wäre eine Erweiterung der Linkmap umd die ausgewählten SliceIDs ;-)

**Comment by joachimdoerr** [comment]
Hallo Marco, das ist ein schwieriges unterfangen. Das Link-NPM-Plugin zu bauen war sehr aufwändig, aktuell bin ich froh, dass es soweit mit der neuen cke5 version läuft. Ich hab nicht vor daran noch etwas zu ändern, jedenfalls nicht wenn ich nicht unbedingt muss.

**Comment by skerbis** [comment]
> Erweiterung der Linkmap 
würde diese lahm machen oder zu einem weitern Fenster führen - hmm

**Comment by joachimdoerr** [comment]
@marcohanke ich denke schon das sowas möglich ist, aber der Aufwand ist erheblich. Ich würde das wie gesagt erstmal nicht machen wollen. Ich persönlich brauche es nicht. Ggf. ergibt sich mal etwas und wir können nochmal darüber nach denken bis dahin close.
