### ISSUE TITLE
YFormLinks funktionieren nicht. 

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/cke5#185]
Da für "field" kein Wert übergeben wird.

**Comment by joachimdoerr** [comment]
4f97c814d581da053db7ce725c6e4c4f1a909e6e

Offensichtlich hat sich da etwas in yform geändert, das widget hatte zuvor das Feld, das jetzt `column` ist im widget als `title` geführt. Das ganze sollte nun wieder funktionieren.

**Comment by skerbis** [comment]
🧐
