### ISSUE TITLE
lite - Profil direkt mitliefern

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/cke5#19]

**Comment by joachimdoerr** [comment]
Was soll das limitierte profile alles beinhalten?

**Comment by skerbis** [comment]
fett, kursiv, link, liste (ordered, unordered) z.B. ... also sehr reduziert, z.B. für sked teaser

**Comment by joachimdoerr** [comment]
Das Profil könnte man dann auch noch in die Demo einbauen.

**Comment by skerbis** [comment]
in der Block-variante würde reichen denke ich

**Comment by joachimdoerr** [comment]
2770dbbd99c897bf0e048dc07f4d6de97ee494ab
