### ISSUE TITLE
Eigene REX_VAR

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/cke5#24]
z.B. `REX_CKE5[id=1 profile=default]`

**Comment by joachimdoerr** [comment]
Für Modul-Input Formulare?

**Comment by skerbis** [comment]
ja

**Comment by skerbis** [comment]
ich mach das für die 1.1

**Comment by skerbis** [comment]
Nicht nötig, da schon sonder einfach einzubinden
