### ISSUE TITLE
Editor Profile übernimmt Einstellungen nicht bei ersten speichern 

### ISSUE THREAD

**Issue by joachimdoerr** [FriendsOfREDAXO/cke5#28]
Erst beim zweiten editieren wird das Editorprofil korrekt übernommen. Strange aber ist so, ich hab noch keine Idee warum das so ist - liegt wohl an dem Tag-Script.

**Comment by skerbis** [comment]
kann ich nicht reproduzieren

**Comment by joachimdoerr** [comment]
Kann das sonst jemand nachstellen?

**Comment by skerbis** [comment]
Tatsächlich habe ich das Problem auch. Bei meinem damaligen Test war wohl was anders.

**Comment by joachimdoerr** [comment]
71a43fe428c5af493639fa482c73cc2d27819796
