### ISSUE TITLE
Eigene Stile definieren

### ISSUE THREAD

**Issue by fietstouring** [FriendsOfREDAXO/cke5#33]
gibts sowas im CKE5?
Also Textbereich markieren, Stil auswählen über Dropdown, wird dann in ein voreingestelltes Tag gewrappt mit Klassennamen etc.

**Comment by joachimdoerr** [comment]
Nein leider gibt es da momentan nichts aber so wie ich das verstanden hab arbeiten ein paar Leute an einem plugin das sowas können soll.

**Comment by joachimdoerr** [comment]
ich werde das nicht als npm plugin für cke5 umsetzen, es ist kein notwendiger Bestandteil für das Addon sofern der Vendor das nicht bietet. Deswegen vorerst Close.
