### ISSUE TITLE
Aufzählungsstile a. b. c. i ii iii iv

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/cke5#34]
..https://github.com/ckeditor/ckeditor5/issues/1031

**Comment by joachimdoerr** [comment]
Wird voraussichtlich morgen releast: https://github.com/ckeditor/ckeditor5/issues/7776

**Comment by joachimdoerr** [comment]
91cbb9e003a3b0a370ca4703f4a8569d2f5df6e5
83803f72e5f805f5092b091387847479f87e298f
cbb68ead25f82d39cf9715c05d71edd061cb25dd
7b5ff1da285466c7b54d3659195da8271e5687dc
