### ISSUE TITLE
French tooltip is displayed in profile editor (also if german language is selected)

### ISSUE THREAD

**Issue by helpy** [FriendsOfREDAXO/cke5#37]
The french text "Cliquez pour éditer" is displayed in profile editor if cursor is moved over a toolbar element:

https://github.com/FriendsOfREDAXO/cke5/blob/768bf094b710d933d3c4a9482924c52e89cf6a3b/assets/vendor/cke5InputTags/cke5InputTags.js#L127

**Comment by joachimdoerr** [comment]
Yes I forgott this problem, the basic javascript resource was created from a french guy. On this point is the wording in the usage case of the profile builder not realy correct - it is not possible to edit the "tag" text. The best strategy for that is the title-text deletion.

**Comment by joachimdoerr** [comment]
153034a29042b4a2aaba53ac3f9ed0e859d796bf
