### ISSUE TITLE
Fehlerhafte Sprachen-Ausgabe

### ISSUE THREAD

**Issue by greatif** [FriendsOfREDAXO/cke5#41]
Im Bereich zum Bearbeiten von Profilen werden nicht alle Textbausteine korrekt in der ausgewählten Sprache ausgegeben.
Das sind die Felder:

- cke5_profile_edit
- cke5_media_manager_type
- cke5_media_category

Im konkreten Fall wurden die spanischen statt der deutschen Begriffe ausgegeben.

**Comment by joachimdoerr** [comment]
ad53854c595abfd79483b4ae0ee39a959687559a
b2757684ecd23aad117be42352105c6f70d24500

bitte mit der neusten master testen

**Comment by greatif** [comment]
Getestet unter PHP 5.6.30 u. 7.1.16 - Profile werden jetzt korrekt in der ausgewählten Sprache ausgegeben.

**Comment by joachimdoerr** [comment]
772668d654847b939cf679a00d4247bacef2d79e
