### ISSUE TITLE
neuer Linktyp: E-Mail

### ISSUE THREAD

**Issue by IngoWinter** [FriendsOfREDAXO/cke5#44]
Es wäre bequem, einen eigenen Button E-Mail Link zu haben. Das "mailto:" von Hand eingeben zu müssen ist irgendwie ein Stilbruch :)

**Comment by skerbis** [comment]
Der Vendor liefert aktuell noch keine fertige Lösung

**Comment by joachimdoerr** [comment]
ich persönlich werde dafür kein npm Modul schreiben. Als ich das für `sub` und `super` gemacht hatte fiel mir das dann nachtärglich auf die Füße, weil der vendor selbst es bereits beim nächsten Update geliefert hatte. Es ist auch nicht die Aufgabe vom Addon die schwächen des Vendors auszugleichen.
