### ISSUE TITLE
unerwünschter Absatz // empty paragraph

### ISSUE THREAD

**Issue by IngoWinter** [FriendsOfREDAXO/cke5#45]
Wenn ich ein Modul mit einer leeren cke eingabemaske speichere, haut er mir ein ```<p>&nbsp;<\/p>``` in die Datenbank.

**Comment by skerbis** [comment]
https://github.com/ckeditor/ckeditor5/issues/401

**Comment by IngoWinter** [comment]
```
rex_extension::register('OUTPUT_FILTER', function ($ep) {
    if (!rex::isBackend())
    {
        $ep->setSubject(str_replace('<p>&nbsp;</p>', '', $ep->getSubject()));
    }
});
```
Dann sollte zumindest sowas in die boot.php, bis die ihren Arsch hochkriegen. Dieser sinnlose Absatz zerhaut einem komplett die Abstände.

**Comment by skerbis** [comment]
na ja, das löst zwar das Problem in der Ausgabe, jedoch nicht in der db. Man könnte es in Modulen durch eine Aktion abfangen. Oder ein js entfernt es aus dem input.

**Comment by IngoWinter** [comment]
Ich habe ein recht umfangreiches "Universalmodul". Mehrspaltigkeit, Text, Bild, Galerie, Video, Formular, Downloads etc. Da habe ich sehr oft leere Textfelder. Ich könnte mir auch andere Fälle sehr gut vorstellen (optionale Bildunterschriften zb).
Natürlich wäre es besser, wenn der Rotz gar nicht erst in der Datenbank landet - aber für die JS Lösung bin ich nicht tief genug im Thema und mir fehlt jegliche Motivation (hab Ohrensausen und Flashbacks von deinem verlinkten Issue bekommen).
Die OPF Lösung ist halt bombensicher und schnell gemacht. Aktion im Modul wäre auch sauber, allerdings von jedem Entwicker für jedes Modul zu setzen.

**Comment by skerbis** [comment]
@IngoWinter wenn die bei CK nix finden, werden wir es hier

**Comment by joachimdoerr** [comment]
Sollen wir hier wirklich etwas bauen? Ich denke das ist die Aufgabe des Moduls per `preSaveAction` so etwas zu bereinigen.

**Comment by skerbis** [comment]
Na ja, da klappt aber nich im YForm oder Meta-Kontext.

**Comment by joachimdoerr** [comment]
es gibt ein pullrequest https://github.com/ckeditor/ckeditor5-engine/pull/1656 ggf. löst sich das problem beim nächsten release.

**Comment by joachimdoerr** [comment]
https://github.com/ckeditor/ckeditor5/issues/1582
8e0cc3117a7582b97ec3237962f46c8930e72f9e
