### ISSUE TITLE
../media vermeiden

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/cke5#46]
Wenn kein MediaManager-Effekt ausgewählt ist, werden die Medien mit ../media eingefügt. Lieber wäre mir /media/

**Comment by staabm** [comment]
Vermutung: ../ funktioniert auch wenn das system in einem unterordner installiert ist. /media geht nur wenn man im root der domain installiert hat

**Comment by joachimdoerr** [comment]
Das Problem ist ja das Frontend auch hier wird dann `../media/` gesetzt. In dem Fall müsste dann der Output manipuliert werden.

**Comment by Koala** [comment]
Auf diesen Umstand müsste in der Beschreibung hingewiesen werden.

Wenn Redaxo in einem Unterverzeichnis installiert ist, dann kann im CK5-Editor unter "Editor Profile" in einem Profil bei den Einstellungen zum "Media-Manager-Type" nicht "default ./media/" ausgewählt werden, da sonst der Pfad zum media-Verzeichnis nicht korrekt ist.
Stattdessen muss einer der "rex_mediaXYZ"-Typen gewählt werden um eine korrekte Medien- Ausgabe zu erhalten.

**Comment by skerbis** [comment]
Option einbauen, damit der User es selbst entscheiden kann, was ihm lieber ist?

**Comment by skerbis** [comment]
../media funktioniert auch nicht wenn ein rewriter aktiv ist.

**Comment by staabm** [comment]
dieses problem ist ja nicht neu und - soweit ich mich erinnern kann - ist es z.b. in tinymce (sogar schon unter R4 zeiten) behandelt gewesen.

fest auf /media loszugehen, ist in meinen Augen eine schlechte Idee. Ein User settings würde ich nur einbauen, wenn man es technisch nicht "automatisch" lösen kann

**Comment by joachimdoerr** [comment]
9ccd4fd410b3749bc77d3e2555edeaa64cb2f13b
