### ISSUE TITLE
Einbinden von Inhalten über externe Buttons

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/cke5#48]
z.B. Snippets, generierte Daten aus yform, Textbausteine oder Ahnliches
So könnte man projektbezogen eigene Funktionen zur Verfügung stellen.

**Comment by tbaddade** [comment]
Sind bereits eigene PlugIns wie in Redactor2 möglich oder soll genau dieses Issue das behandeln?
Ein Beispiel wären Textstellen mit Links zu einem YForm Datensatz zu verknüpfen.

**Comment by skerbis** [comment]
@tbaddade z.B. aber das ganze sehr variabel und vor allem ohne extra Plugin.

**Comment by tbaddade** [comment]
Eigene JS-PlugIn-Datei fände ich gut. Das erspart das kopieren von Instanz A zu Instanz B. 

Ich bin aber mal gespannt wie ihr es lösen werdet.

**Comment by skerbis** [comment]
@tbaddade aktuell sind externe Plugins im Build-Prozess von CKE5 nicht vorgesehen - oder @joachimdoerr? Man muss, soweit ich verstanden habe ,die Plugins immer komplett im Build anbieten.

**Comment by skerbis** [comment]
Das erhielt ich als Antwort: 
https://ckeditor.com/docs/ckeditor5/latest/builds/guides/faq.html#where-are-the-editorinserthtml-and-editorinserttext-methods-how-to-insert-some-content

**Comment by joachimdoerr** [comment]
Man kann also ein eigenes npm Modul dafür bauen oder ein JS konstruieren, dass den Editor "beliefert"... viel Arbeit...

**Comment by skerbis** [comment]
ok close
