### ISSUE TITLE
Bild verlinken

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/cke5#55]
Bilder lassen sich nicht verlinken. Issue im CKE5 Repo ist auch schon raus.
https://github.com/ckeditor/ckeditor5/issues/1207

**Comment by skerbis** [comment]
https://github.com/ckeditor/ckeditor5-image/issues/230

**Comment by joachimdoerr** [comment]
ich Werder hier kein extra npm Modul schreiben. Also das cke5 redaxo addon kann hier nichts ausrichten, dass muss von Vendor angeboten werden.
