### ISSUE TITLE
Umbau des internen JS Triggers von pjax:success zu rex:ready

### ISSUE THREAD

**Issue by dergel** [FriendsOfREDAXO/cke5#56]
Da im Core rex:ready als Status getriggert wird und Standard ist, wäre dieser Umbau super, da dies dann auch kompatibel zur YForm wäre, auch wenn es im Moment noch funktioniert. Dadurch wird auch doppeltes unkontrolliertes triggern vermieden.

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/cke5/pull/58
