### ISSUE TITLE
Anleitung zur Verwendung

### ISSUE THREAD

**Issue by joachimdoerr** [FriendsOfREDAXO/cke5#6]
Die Demo ist schick aber man findet keinen Hinweis wie man den Editor einbinden kann. Das sollte durch ein Demo-Modul erledigt werden. Oder eine entsprechende Anleitung im Overview - Ggf. mit eigenem Link. Eventuell auch das Doku Plugin aber das macht dann schon wieder so massig Arbeit...

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/cke5/blob/master/README.md
