### ISSUE TITLE
Update 2.0.1 > 3 error

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/cke5#65]
> Class 'Cke5\Creator\Cke5ProfilesCreator' not found

https://github.com/FriendsOfREDAXO/cke5/blob/e2270a6edbc58dde69650dcf4375804c9df97c36/update.php#L15

**Comment by joachimdoerr** [comment]
an der stelle hat der autoloader noch keine neuen resourcen geladen. wahrscheinlich weil die update.php im selben prozess aufgerufen wird wird im dem auch das entpacken und schreiben des packets durch den installer geschieht.

**Comment by staabm** [comment]
Die update.php sollte keine externen Abhängigkeiten haben. Sie wird in manchen Fällen nur die Klassen zugreifen können die die „alte version“ des Addons beinhaltet/geladen hat

**Comment by joachimdoerr** [comment]
e3c5ea1e1735c30dbd08c8b0bd3428fa83e598f2
