### ISSUE TITLE
Datenbanktabellenprefix fest verdongelt

### ISSUE THREAD

**Issue by Koala** [FriendsOfREDAXO/cke5#66]
Das Datenbanktabellenpräfix ist mit *rex_* fest in der Datei data.sql verdongelt.
Das bringt Probleme, wenn in der Grundkonfiguration ein anderes Tabellenpräfix angegeben wurde. Hier muss die Installation unbedingt angepasst werden!
Eine Installation des Addons über den Installer ist damit nicht möglich.

**Comment by joachimdoerr** [comment]
f2d55f634963d30ab7da710c8ace186633faf9bd
