### ISSUE TITLE
Installation nicht möglich

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/cke5#69]
Die Tabelle cke5_profiles existiert noch nicht!

![image](https://user-images.githubusercontent.com/330516/50969689-8c8faf00-14df-11e9-8d7d-c729426fdb2c.png)

![image](https://user-images.githubusercontent.com/330516/50969730-a4ffc980-14df-11e9-9e4b-670c2f294e7e.png)

**Comment by staabm** [comment]
welche addon version? welche redaxo version?

**Comment by olien** [comment]
Sorry. Beides die aktuellsten (Beta) Versionen aus dem installer

**Comment by skerbis** [comment]
Update oder frische Installation. Eine cke5 Beta gibt es nicht

**Comment by staabm** [comment]
Mich wundert dass hier irgendwas bzgl „tablespaces“ in der Fehlermeldung kommt.

Damit arbeiten wir in redaxo gar nicht

**Comment by skerbis** [comment]
Ich habe es gerade bei mir in einer frischen beta-1 getestet ... kein Problem hier

**Comment by olien** [comment]
hm. probiere ich später nochmal...

**Comment by olien** [comment]
Ging mit einer frischen Installation (CMS+Addon)
