### ISSUE TITLE
readme updaten key shortcuts

### ISSUE THREAD

**Issue by joachimdoerr** [FriendsOfREDAXO/cke5#70]
Wer hat lust mitzuhelfen? Es müssten mal die Tastaturkürzel gecheckt und ggf. in der readme für DE und EN upgedated werden.

**Comment by skerbis** [comment]
@crydotsnake ? Hast du Lust?

**Comment by crydotsnake** [comment]
@skerbis Gerne, nur hab ich Leider nur am Wochenende Zeit.

**Comment by joachimdoerr** [comment]
@crydotsnake top Dank Dir! Das eilt nicht nur nach ein paar Ckeditor 5 Editor-updates sollten wir das mal checken damit wir hier aktuell bleiben.

**Comment by crydotsnake** [comment]
@joachimdoerr @skerbis Ich werde mich am Wochenende dransetzen und euch dann Bescheid geben ! :).

**Comment by joachimdoerr** [comment]
@crydotsnake am besten einfach nur mit dieser Tabelle abgleichen: https://ckeditor.com/docs/ckeditor5/latest/features/keyboard-support.html

**Comment by crydotsnake** [comment]
@joachimdoerr Sieht soweit alles richtig aus.

**Comment by joachimdoerr** [comment]
ok dann Close.
