### ISSUE TITLE
mblock :: medienpoolbutton

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/cke5#71]
In vorhandenen Blocks kann der Medienpool-button nicht verwendet werden. 
In neuen Instanzen funktioniert er. 

Folgender Fehler in der Console
```
CKEditorError: model-createPositionAt-offset-required: Model#createPositionAt() requires the offset when the first parameter is a model item. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-model-createPositionAt-offset-required
```

**Comment by joachimdoerr** [comment]
das liegt offensichtlich nicht an MBlock, das problem taucht immer dann auf wenn mehr als eine CKE5 Instanz vorhanden ist.

**Comment by joachimdoerr** [comment]
Es kommt tatsächlich doch nur in Verwendung mit MBlock vor.

**Comment by MC-PMOE** [comment]
Bei mir taucht derselbe Fehler unter Verwendung des Codebeispiels für MForm auf ohne das MBlock im Modul beteiligt ist.

**Comment by MC-PMOE** [comment]
Habe zum Test die 3.0.0 installiert, mit der funktioniert alles wie erwartet.

**Comment by skerbis** [comment]
Also der Fehler hat sich in der 3.1 eingeschlichen?

**Comment by MC-PMOE** [comment]
Ja mit der 3.0.0 läuft mit meinen Tests alles normal

**Comment by joachimdoerr** [comment]
das Problem dabei ist, es kann viele Ursachen haben, zum einen die neue CKE5 Version zum anderen das neue rex:ready handling

**Comment by joachimdoerr** [comment]
f38b0994025b104bb5e5565537bb5e82d1268470
