### ISSUE TITLE
Charmap Integration

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/cke5#74]
In Slack hatten wir es gerade von geschützten Leerzeichen die aktuell nicht funktionieren. Eine Charmap wäre cool damit dieses ganze Geraffel nutzbar wird.
Falls nicht möglich wäre es schon mal ein Anfang 
```
editor.keystrokes.set( 'Alt+space', ( key, stop ) => {
    editor.execute( 'input', { text: '\u00a0' } );
    stop();
} );

```
zu integrieren

**Comment by joachimdoerr** [comment]
@marcohanke ich bräuchte dazu etwas mehr Kontext, hab grade keine Vorstellung weswegen das benötigt wird.

**Comment by marcohanke** [comment]
Im Tiny gabs immer ein Button mit einer charmap, da konnte man dann sämtliche Sonderzeichen per Klick einfügen

**Comment by skerbis** [comment]
https://github.com/ckeditor/ckeditor5/issues/1110

**Comment by skerbis** [comment]
ist lt. aktueller Roadmap vorgesehen: https://github.com/ckeditor/ckeditor5/issues/5653

**Comment by joachimdoerr** [comment]
https://ckeditor.com/docs/ckeditor5/latest/features/special-characters.html

**Comment by joachimdoerr** [comment]
Das kann ich leider nicht für release 4.0.0 einbauen. es wirft viele Probleme auf, die der CKE5 Vendor mit sich bringt. Plugins laden und ausschließen bereitet leider diverse Probleme weswegen das erst eingebaut werden kann sobald der vendor entsprechende bugs behoben hat.

**Comment by joachimdoerr** [comment]
Könnte so funktionieren: 

```         // init editor
        ClassicEditor.create(document.querySelector('#' + unique_id), options)
            .then(editor => {
                ckeditors[unique_id] = editor; // Save for later use.
                cke5_pastinit(element, sub_options);

                editor.plugins.get( 'SpecialCharacters' ).addItems( 'a', [
                    { title: 'D simple arrow left', character: '←←' },
                    { title: 'simple arrow up', character: '↑' },
                    { title: 'simple arrow right', character: '→' },
                    { title: 'simple arrow down', character: '↓' }
                ] );

            })
            .catch(error => {
                console.error(error);
            });
    }
```

**Comment by joachimdoerr** [comment]
@marcohanke dein spezielles Problem sollte mit Transform from to abgehandelt werden können siehe Screenshot
<img width="2242" alt="Bildschirmfoto 2020-07-14 um 17 08 37" src="https://user-images.githubusercontent.com/1191549/87442578-c077f300-c5f4-11ea-8bcb-e5c89c923162.png">

**Comment by marcohanke** [comment]
Moinsen, im Changelog steht 'add special characters plugins' ist das das oder gibts noch eine andere Möglichkeit? Ansonsten ist das schon mal ein Workaround, danke dir!

**Comment by skerbis** [comment]
@marcohanke das sind transformations
