### ISSUE TITLE
No images show with yrewrite active

### ISSUE THREAD

**Issue by 191977** [FriendsOfREDAXO/cke5#75]
Hi,
I recently noticed that I will not get images shown in the backend and frontend if yrewrite htaccess is set with its default settings and no Media-Manager-Type is set in the cke5 profile. As soon as I set a Media-Manager-Type or get rid of the htaccess everything works smoothly. I did a fresh install with only cke5 and yrewrite active to confirm that it's there from the start. I tested with the default profile.
For testing I deleted lines 94 to 101 from the htaccess which didn't help. 

I can provide access to the fresh install if that is of any help.
[htaccess.txt](https://github.com/FriendsOfREDAXO/cke5/files/3456042/htaccess.txt)

**Comment by skerbis** [comment]
You should setup the media path in CKE5 in the profile you use. Add a custom path like /media/yourmediamanagereffect/

**Comment by 191977** [comment]
Ah I see. From the start the path is set to media which I want in that case because I don't use a media manager effect here.  But it seems to be only some sort of placeholder. As soon as I make any change to the path it will get stored and it works. Even if I go back to the default of "media".

**Comment by 191977** [comment]
Thanks for your help! It might be helpfull for new users to actually set the prepopulated path. Regarding my Issue with it we can close this if you want. I do now know how to handle it in the future :-)

**Comment by skerbis** [comment]
@joachimdoerr anscheinend wird der media path bei der Installation nicht im Profil gespeichert. Dies gilt auch für die Sprache

**Comment by joachimdoerr** [comment]
We have to update the data.sql and the javascript files there will be saved to the assets folder.

**Comment by joachimdoerr** [comment]
23f598770f5c7c6a701f3907b492ccd1c815d0aa
e817edda55d780dcde371e2c1e2384f5ad8f1984
