### ISSUE TITLE
Profiles Creator: Fehlende Option 'default' bei FontSize

### ISSUE THREAD

**Issue by isospin** [FriendsOfREDAXO/cke5#76]
Im Profil Editor fehlt bei den Werten für die Schriftgröße der Wert 'default': https://github.com/FriendsOfREDAXO/cke5/blob/80f79b9ee5e4125bac5670449aed5533117f4471/lib/Cke5/Creator/Cke5ProfilesCreator.php#L35
Wenn das Formularfeld 'Schriftgrößen' im Editor leer bleibt, wird die Reset-Option 'default/Standard' im Editor angezeigt. Sobald hier Werte vorausgewählt werden, fehlt die Möglichkeit 'default/Standard' auszuwählen

**Comment by joachimdoerr** [comment]
4fb2dfdd202e657ebdd63793e086e9f1e9e9dcea
