### ISSUE TITLE
CSS Styles und Readmy updaten

### ISSUE THREAD

**Issue by joachimdoerr** [FriendsOfREDAXO/cke5#83]
Durch den IMG Resize haben sich ggf. die frontend css geändert? @skerbis kannst Du das checken?

**Comment by skerbis** [comment]
es gibt zwar eine neue class: `image_resized` diese hat aber auf unsere bestehenden Stile keine Auswirkung. - Die Breiten der Bilder werden direkt als style-attribut übergeben. Skripte könnten hier ansetzen. Tatsächlich. Sehe ich im REDAXO-Umfeld keinen Sinn für den Resizer. 

Check
