### ISSUE TITLE
Fontfamily optionen hinzufügen 

### ISSUE THREAD

**Issue by joachimdoerr** [FriendsOfREDAXO/cke5#84]
Es ist momentan nicht möglich nur bestimmte standard schriften wählen zu können, hier müss eine multiple select her. es muss auch geprüft werden ob das auch mit google fonts arbeiten kann

**Comment by skerbis** [comment]
wenn überhaupt würde ich es auf lokale Fonts beschränken, die z.B. in /assets/fonts/ abgelegt werden.

**Comment by skerbis** [comment]
Check
