### ISSUE TITLE
seltsames Verhalten beim Profil anlegen mit Überschriften 

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/cke5#86]
![image](https://user-images.githubusercontent.com/3855487/71593074-d596a400-2b32-11ea-868f-61658d5d6b72.png)

Erzeugt bei `Überschrift 1` eine `<h2>`, bei `Überschrift 2` eine `<h3>`, usw. 

Wenn ich den Paragraph nach hinten verschiebe, passt alles.

**Comment by joachimdoerr** [comment]
Kann ich nicht nachstellen. Ggf. wurde das Problem bereits mit einem Vendorupdate gelöst.
