### ISSUE TITLE
Profil bearbeiten: Enter schickt Formular ab

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/cke5#87]
Wenn ich einen Button hinzufügen will und diesen eintippe, dann mit Enter bestätige, wird das Formular abgesendet statt den Button zu übernehmen.

**Comment by tbaddade** [comment]
Kann ich so bestätigen

**Comment by joachimdoerr** [comment]
Ja generell soll man ja keine Buttons "eintippen", deswegen sind ja alle möglichen buttons vordefiniert zu Auswahl vorhanden.

**Comment by alexplusde** [comment]
Das legt das Eingabefeld leider irgendwie nahe - andere dieser inline-select-Eingabefelder kommen eigentlich damit klar, vielleicht kann man das tauschen?

**Comment by tbaddade** [comment]
Eine Sortierung der Liste würde das Durchsuchen vermutlich vereinfachen. Eine direkte Eingabe der Buttons fände ich aber sinnvoller, sodass man eben auch h1, h2 etc. direkt notieren könnte.

**Comment by joachimdoerr** [comment]
@tbaddade  @alexplusde : Freunde wenn euch das stört bitte ändern und Pull-Request. Das ist kein großes Hexenwerk sonder ein ganz normales Javascript das hier als Vendor genutzt wird. Das kann jeder Webdesigner mit ein bisschen JS Erfahrung und Basiswissen ändern. Ich finde es ja super, dass es viele Issues gibt, aber auch wirklich unschön, dass es bei FOR Addons generell aus der Community eine NULL-Beteiligung bei der Lösungsherbeiführung gibt.

**Comment by tbaddade** [comment]
> dass es bei FOR Addons generell aus der Community eine NULL-Beteiligung bei der Lösungsherbeiführung gibt.

Da sprichst du jetzt aber die Richtigen an ;)

Zum Issue selbst: Wir hatten das AddOn damals im Test und ist bei uns aus bekannten Gründen nicht mehr aktiv. Daher wird es von mir hier keinen PR geben.

@alexplusde Entscheide du bitte, ob das Issue noch offen bleiben soll.

**Comment by alexplusde** [comment]
> Da sprichst du jetzt aber die Richtigen an ;)

Das dachte ich mir auch.

Es ist nicht gelöst. Von mir aus bleibt es dann halt 5 Jahre offen, bis das Addon obsolet ist oder sich früher jemand findet.

**Comment by skerbis** [comment]
> Eine direkte Eingabe der Buttons fände ich aber sinnvoller
@tbaddade  das geht bereits indem du h1 gefolgt von einem , eintippst 
Das andere genannte Problem ist mir nie aufgefallen. Lässt sich aber sehr einfach lösen.

**Comment by joachimdoerr** [comment]
db80ecf100aff03399f81a5cfd4cbaae8d9b641c
