### ISSUE TITLE
cke5 css blendet picture-Element im Backend aus

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/cke5#88]
https://github.com/FriendsOfREDAXO/cke5/blob/92615ae02b0976dcde5880e3f789478539f20611/assets/cke5.css#L77-L82

Erster Gedanke: wtf
Zweiter Gedanke: wtf
Dritter Gedanke: wtf

Gibt es einen guten Grund, warum das gemacht wird?

**Comment by tbaddade** [comment]
@joachimdoerr @skerbis Könnt hier etwas zu sagen, warum das so gemacht wird?
