### ISSUE TITLE
manuelle LinkDecorator je Profil hinzufügen können.

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/cke5#90]
https://ckeditor.com/docs/ckeditor5/latest/api/module_link_link-LinkDecoratorManualDefinition.html

Ermöglichen, zusätzliche Attribute an einem Link hinzuzufügen, z.B. `rel` oder weitere Attribute, die das Aussehen beeinflussen können (`data`-Attribute, Klassen, etc.)

**Comment by joachimdoerr** [comment]
Ja jetzt müsste man das nur noch im Node Link Modul einbauen https://github.com/basecondition/ckeditor5-rexlink ich würd mich hier auch über Unterstützung von JS Experten freuen.

**Comment by joachimdoerr** [comment]
3cfa31e925bceb1ee0621dd090e14bfc6e711764
