### ISSUE TITLE
Profilseite verwirrend

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/cke5#91]
Ich editiere grad das default Profile.

Ich lösche die Buttons bei "Text Ausrichtung" und speichere. Die Preview zeigt dennoch die "Text Ausrichtung" weiterhin an. Sie verschwindet erst, wenn man in der Toolbar zusätzlich "alignment" löscht. Man muss doppelt löschen. Das ist auch so mit anderen Buttons.

Hatte so auch die Farben deaktiviert. Jetzt sind die Felder mit dem Toggle komplett verschwunden.

Ich weiß, das Backend gibt da nicht viel her, aber eventuell helfen schon Erklärtexte und das ganze ein wenig anders zu strukturieren.

**Comment by joachimdoerr** [comment]
@tbaddade naja man könnte das Profil auch irgendwie via Ajax reloaden oder so. Vielleicht kannst du dem ja mal nachgehen und ein Pull-Request stellen.
