### ISSUE TITLE
Profil : Überschriften in die Toolbar

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/cke5#92]
Wie bekommt man einzelnen Überschriften direkt in die Toolbar, ohne das man das Dropdown "heading" aktivieren muss?

**Comment by tbaddade** [comment]
Könnte hier jemand helfen?

**Comment by joachimdoerr** [comment]
Du willst das Heading Element nicht und statt dessen H1, H2... buttons? Ich hab noch nicht getestet ob der Vendor das überhaupt anbietet. Das müsstest du mal Recherchieren, wenn ja können wir das gerne im Profil-Editor hinzufügen. An Sonaten geht das momentan so nicht.
