### ISSUE TITLE
Säuberungsmethode

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/cke5#93]
Gibt es ein Säuberungscode der leere Tags und wie das hier wieder löscht?

`<p style="margin-left:0.0px;">`

Der Text war reiner Fließtext. Nur der Absatz davor wurde als Überschrift markiert. Weder bekam der Text einen Einzug noch wurde dieser als Liste umgesetzt. Woher kommen diese Styleangaben?

**Comment by tbaddade** [comment]
Hat jemand eine Idee wie man das anpassen/entfernen kann?

**Comment by tbaddade** [comment]
Auf das ich mich wiederhole … wie bekommt das weg?

<img width="403" alt="Bildschirmfoto 2020-01-23 um 17 16 51" src="https://user-images.githubusercontent.com/338267/73002378-3e0c3480-3e04-11ea-96c9-de68d4b10bc1.png">

So ist der Editor leider kaum zu gebrauchen.

**Comment by joachimdoerr** [comment]
Der Editor schreibt sowas von Haus aus nicht in den Code. Hast du irgendwelche anderen JS Skripte oder OutputFilter die das reinhängen könnten?

**Comment by tbaddade** [comment]
Nein. Ich kopieren nur Text hinein.

**Comment by alexplusde** [comment]
Habe das Problem auch.

**Comment by marcohanke** [comment]
Hier das gleiche. Gelegentlich beim reinkopieren. Formate löschen hilft übrigens nichts.

**Comment by tbaddade** [comment]
Da die Entwicklung eingestellt wurde, schließe ich.

**Comment by alexplusde** [comment]
Blöd, dass ich den noch auf Empfehlung gerade in sämtlichen Installationen nutze. Möchte an dieser Stelle noch mal meine Unzufriedenheit kund tun - dass Projekte sterben, damit kann ich leben.

**Comment by joachimdoerr** [comment]
@tbaddade warum wird das Addon hier als gestorben deklariert? @alxndr-w der Addon Author für CKE5 also ich haben bis heute die Entwicklung nicht eingestellt und ich hab es auch auf weiteres nicht vor.

**Comment by alxndr-w** [comment]
@joachimdoerr da wollte ich dir nicht zu nahe treten.

2 Jahre später auf das Issue zu reagieren würde ich nicht unbedingt als gestorben bezeichnen, wohl aber als apathisch. ;) Bitte nicht zu ernst nehmen.
