### ISSUE TITLE
data-lang sollte automatisch die Backendsprache verwenden

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/cke5#94]
Ich meine, dass man nicht ständig `data-lang` notieren muss.
```
<textarea class="form-control cke5-editor" data-profile="profile" data-lang="'.Cke5\Utils\Cke5Lang::getUserLang().'" name="" rows="5"></textarea>
```

**Comment by joachimdoerr** [comment]
Ja tut es das nicht wenn du den data-lang tag weg lässt?

**Comment by tbaddade** [comment]
Ich musste das Attribute angeben, da ansonsten der Editor nicht initialisiert wurde.

**Comment by tbaddade** [comment]
Da die Entwicklung eingestellt wurde, schließe ich.

**Comment by joachimdoerr** [comment]
@tbaddade die Entwicklung wurde nicht eingestellt.

**Comment by tbaddade** [comment]
> die Entwicklung wurde nicht eingestellt.

@joachimdoerr Danke für die Info. Dann hatte ich deinen Post im Slack damals falsch gedeutet.

**Comment by joachimdoerr** [comment]
@tbaddade nein zu dem Zeitpunkt wollte ich den Supporten einstellen, hab mich dann aber doch nochmal dazu durchgerungen es weiter zu machen, da sonst der cke5 als einziger editor der wirklich smart mit mblock läuft weg brechen täte.

**Comment by joachimdoerr** [comment]
Ich hab das grade nochmals geprüft, der Editor initialisiert auch ohne data-lang, hier wird dann die default lang des editors genommen.
