### ISSUE TITLE
Button removeFormat hat keine Auswirkungen

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/cke5#96]
Der Button scheint keine Auswirkungen zu haben.

1/ Habe den Button hinzugefügt. 
2/ Markiere den kompletten Text, um zum Bsp. dieses `margin-left: 0.0px` weg zu bekommen
3/ Der Button bleibt disabled

**Comment by joachimdoerr** [comment]
Ich kann nicht nachvollziehen was du erreichen willst? Der Remove Button entfernt Formatierungen die Du durch den Editor vorgenommen hast.

**Comment by tbaddade** [comment]
Das macht er eben nicht. Setze mal eine Überschrift und paar Absätze. Der Button bleibt disabled.

**Comment by tbaddade** [comment]
Da die Entwicklung eingestellt wurde, schließe ich.
