### ISSUE TITLE
Übernahme aus Texteditor werden styles notiert

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/cke5#97]
Text von Sketch in VisualStudioCode kopiert von dort in den Cke.

**VisualStudioCode**
<img width="557" alt="Bildschirmfoto 2020-01-23 um 12 34 19" src="https://user-images.githubusercontent.com/338267/72981262-af37f180-3ddc-11ea-9058-9939c2c01cb1.png">

**cke5**
<img width="225" alt="Bildschirmfoto 2020-01-23 um 12 34 54" src="https://user-images.githubusercontent.com/338267/72981315-caa2fc80-3ddc-11ea-82e0-62342bb66777.png">

Das klappt sogar über PHPStorm ;) 

**PHPStorm**
<img width="314" alt="Bildschirmfoto 2020-01-23 um 12 35 58" src="https://user-images.githubusercontent.com/338267/72981380-eb6b5200-3ddc-11ea-8fcd-805905e315ff.png">

**cke5**
<img width="244" alt="Bildschirmfoto 2020-01-23 um 12 36 16" src="https://user-images.githubusercontent.com/338267/72981398-f7571400-3ddc-11ea-8e5a-60e5ed0f3399.png">

**Comment by joachimdoerr** [comment]
@tbaddade ist das nicht eine vendor Sache? oder gibt es ein setting für den editor sowas zu umgehen, ich hab da jetzt grade nicht den überblick. Du kannst das aber gene mal recherchieren und Rückmelden ggf. können wir das, sollte es via setting einstellbar sein, im Profil-Editor hinzufügen.
