### ISSUE TITLE
Problem mit mform / mblock

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/cke5#99]
Moin, ich habe ein wirklich fettes Modul welches den CKE 20 mal enthält..

Wenn ich einen Slice editieren möchte dauert es bis zu 8 Sekunden (ajax loader) bis ich auch editieren kann. Bei deaktiviertem CKE sehe ich den ajax loader kaum und ich kann quasi sofort editieren...

Im Quellcode wird das erzeugt:

![image](https://user-images.githubusercontent.com/330516/73525545-b29c3000-440f-11ea-9dbd-2978b68adbd7.png)

mblock: 3.1.0
mform:  5.3.1
cke: 3.7.1

LG
Oliver

**Comment by olien** [comment]
Hm. Scheint wohl normal und notwendig(?) zu sein.

![image](https://user-images.githubusercontent.com/330516/74015629-48e0d080-4991-11ea-95cf-488eaec48084.png)

Wenn während des editieren weitere CKE Felder hinzukommen ist das ja kein Problem. Wenn es allerdings initial schon viele gibt schon. Wie machen die anderen Editoren das? Mit redactor / markitup gibt es das Problem nicht.

**Comment by joachimdoerr** [comment]
Das wird jetzt jeweils in ein wrapper gesteckt. Das kommt sonst vom Vendor, da können wir nicht viel machen aber wo es nun im wrapper steckt ck-body-wrapp ist es nicht mehr so unschön an den DOM gepackt.
